apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: tomcat
        image: tomcat 
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: conf
          mountPath: /usr/local/tomcat/conf/server.xml
          subPath: server.xml
        - name: conf
          mountPath: /usr/local/tomcat/conf/context.xml
          subPath: context.xml
      volumes:
        - name: conf
          configMap:
            name: files
            items:
            - key: context.xml
              path: context.xml
            - key: server.xml
              path: server.xml
